spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
server.port=8000
# For >2.5.0
spring.jpa.defer-datasource-initialization=true

#spring.config.import=optional:configserver:http://localhost:8888

environmenttype=Dev Environment (currency-exchange)

#For Eureka client
#URL of the Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761
#Register this app with Eureka
eureka.client.register-with-eureka=true
#Fetch registry from Eureka
eureka.client.fetch-registry=true