spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
server.port=8000

# For >2.5.0
spring.jpa.defer-datasource-initialization=true

#spring.config.import=optional:configserver:http://localhost:8888

#For Eureka client
#URL of the Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#Register this app with Eureka
eureka.client.register-with-eureka=true
#Fetch registry from Eureka
eureka.client.fetch-registry=true

# Eureka Client Configuration Always prefer IP address for registration and discovery
# To avoid issues in environments where hostname resolution might be problematic, such as Docker or Kubernetes
eureka.instance.prefer-ip-address=true