spring.application.name=currency-exchange


#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.h2.console.enabled=true
#server.port=8000
## For >2.5.0
#spring.jpa.defer-datasource-initialization=true
spring.config.import=optional:configserver:http://localhost:8888

# Eureka Client Configuration Always prefer IP address for registration and discovery
# To avoid issues in environments where hostname resolution might be problematic, such as Docker or Kubernetes
eureka.instance.prefer-ip-address=true


# Zipkin Tracing Configuration
management.tracing.sampling.probability=1.0
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
# Use environment variable with default value for Zipkin endpoint
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

# Actuator endpoints
management.endpoints.web.exposure.include=*

# Optional: Show trace ID in logs
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]


logging.level.com.anil.springboot.currency_exchange=DEBUG