spring.application.name=Config-Server
server.port=8888

# ? Use GitHub remote URI directly (most reliable)
spring.cloud.config.server.git.uri=https://github.com/ravvaanilkumar/LearningRepository
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.timeout=10
spring.cloud.config.server.git.refresh-rate=0

# For local
#spring.profiles.active=native
#spring.cloud.config.server.native.search-locations=classpath:/config

# ? COMPLETELY disable config client on the server itself
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
#spring.config.import=

#logging.level.org.springframework.cloud.config=DEBUG
#logging.level.org.eclipse.jgit=DEBUG